# Generated by Django 4.2.5 on 2023-10-08 16:38

from django.db import migrations, models
import inventario.validators


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, validators=[inventario.validators.validation_categoria])),
            ],
            options={
                'permissions': [('reporte_cantidad', 'Visualizar la cantidad reporte'), ('reporte_detalle', 'Reporte detallado de cantidades')],
            },
        ),
        migrations.CreateModel(
            name='Supermercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, validators=[inventario.validators.validation_categoria])),
            ],
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={},
        ),
    ]
